import type { Order } from '@/domain/commerce/types';

/**
 * Clearly fake order used only to preview the receipt template in Admin → Receipts.
 * It is never stored, and it is flagged `isDemo` so the sheet prints the "demo" marker.
 */
export const SAMPLE_RECEIPT_ORDER: Order = {
  id: 'sample-receipt-preview',
  orderNumber: 'MS-0000-000000',
  createdAt: '2026-01-15T12:00:00.000Z',
  updatedAt: '2026-01-15T12:00:00.000Z',
  locale: 'ar',
  status: 'new',
  paymentMethod: 'cod',
  paymentStatus: 'cod_pending',
  customer: {
    name: 'عميل تجريبي · Sample customer',
    phone: '01000000000',
    phoneDisplay: '010 0000 0000',
    email: 'customer@example.invalid',
  },
  fulfillment: {
    method: 'delivery',
    pickupBranch: null,
    governorate: null,
    area: null,
    address: 'عنوان تجريبي · Sample address',
    notes: null,
    eta: null,
    courier: null,
    trackingNumber: null,
  },
  items: [
    {
      lineNo: 1,
      productSlug: 'sample-product',
      productName: { ar: 'منتج تجريبي للمعاينة', en: 'Sample product (preview)' },
      brandName: null,
      variantLabel: { ar: '١٢٨ جيجابايت · أسود', en: '128 GB · Black' },
      options: [],
      imageUrl: null,
      sku: 'SAMPLE-SKU-1',
      warranty: { ar: 'ضمان تجريبي', en: 'Sample warranty' },
      regularUnitPrice: 1000,
      unitPrice: 1000,
      quantity: 1,
      lineSubtotal: 1000,
      discountAmount: 0,
      lineTotal: 1000,
      appliedOffer: null,
      discounts: [],
      isGift: false,
    },
  ],
  totals: {
    originalSubtotal: 1000,
    subtotal: 1000,
    discountTotal: 0,
    shippingFee: null,
    shippingFeeStatus: 'pending',
    total: 1000,
    paidAmount: 0,
    remainingAmount: 1000,
    splitDepositAmount: null,
  },
  promoCode: null,
  customerNote: null,
  reservationExpiresAt: null,
  stockCommitted: false,
  reviewPending: false,
  canCancel: false,
  cancelledAt: null,
  isDemo: true,
  timeline: [],
};
