import { resolveLocalized } from '@/domain/localized';
import { useSettings } from '@/features/settings/context';
import { useI18n } from '@/i18n/context';
import styles from './BrandLogo.module.css';

/** Source-of-truth logo file; optimized derivatives are generated by `npm run brand:icons`. */
const DEFAULT_LOGO_SRC = '/brand/malek-store-logo.png';

interface BrandLogoProps {
  size?: 'sm' | 'md' | 'lg';
  withWordmark?: boolean;
  /** Put the mark on a white tile (for dark backgrounds, keeps the black "M" visible). */
  tile?: boolean;
  /** Decorative when a sibling already names the brand (e.g. inside a labelled link). */
  decorative?: boolean;
  className?: string;
}

export function BrandLogo({
  size = 'md',
  withWordmark = false,
  tile = false,
  decorative = false,
  className,
}: BrandLogoProps) {
  const { brand } = useSettings();
  const { locale } = useI18n();
  const alt = decorative || withWordmark ? '' : resolveLocalized(brand.logo.alt, locale);
  const isDefault = brand.logo.src === DEFAULT_LOGO_SRC;

  const image = (
    <img
      className={styles.mark}
      src={isDefault ? '/brand/malek-store-mark-192.webp' : brand.logo.src}
      srcSet={
        isDefault
          ? '/brand/malek-store-mark-96.webp 96w, /brand/malek-store-mark-192.webp 192w, /brand/malek-store-mark-384.webp 384w'
          : undefined
      }
      sizes={size === 'lg' ? '64px' : size === 'md' ? '40px' : '32px'}
      width={192}
      height={189}
      alt={alt}
      decoding="async"
    />
  );

  return (
    <span className={[styles.brand, styles[size], className].filter(Boolean).join(' ')}>
      {tile ? <span className={styles.tile}>{image}</span> : image}
      {withWordmark && <span className={styles.wordmark}>{brand.name}</span>}
    </span>
  );
}
