-- Deterministic timeline ordering.
-- Activities written in the same transaction share one timestamp (now()), and the timeline used the random UUID as
-- tie-breaker, so same-instant events had an arbitrary order. A monotonically increasing insertion number gives a
-- stable, meaningful secondary key: timeline = occurred_at desc, seq desc.
-- Additive only: no existing column, timestamp or event is modified (existing rows are simply numbered).
alter table public.activities add column if not exists seq bigint generated by default as identity;
create index if not exists activities_lead_time_seq_idx on public.activities (lead_id, occurred_at desc, seq desc);
