-- ════════════════════════════════════════════════════════════════════════════
-- MALEK STORE · DEMO seed (sample data for previews — every row has is_demo = true)
-- GENERATED by scripts/seed/generate-seed-sql.mjs from supabase/seed/data/demo/manifest.json.
-- Do not edit by hand. Remove at any time with: select public.delete_all_demo_data();
-- Never run this against a production database you intend to launch without demo cleanup.
-- ════════════════════════════════════════════════════════════════════════════

-- No demo datasets yet (the demo catalog, offers and campaigns arrive in Phase 02).
select 1;
