// ─────────────────────────────────────────────────────────────────────────────
// DEMO CATALOG SOURCE (authoring format). `npm run seed:generate` expands this into
// supabase/seed/data/demo/catalog.json (+ generated media) which feeds BOTH the demo frontend
// and supabase/seed/demo.sql. Everything here is SAMPLE data:
//   • prices and stock are fictional sample values, not Malek Store prices;
//   • specifications are illustrative placeholders (flagged in the UI), never verified claims;
//   • iPhone 18 Pro / Pro Max / iPhone Duo are owner-supplied campaign names — their details are
//     "to be confirmed" rather than invented.
// Relative dates ("+5d", "-3d", "+36h") are resolved against "now" when data is loaded/seeded.
// ─────────────────────────────────────────────────────────────────────────────

const L = (ar, en) => ({ ar, en });

export const COLORS = {
  black: { label: L('أسود', 'Black'), hex: '#1d1d1f' },
  white: { label: L('أبيض', 'White'), hex: '#f2f1ec' },
  silver: { label: L('فضي', 'Silver'), hex: '#d6d7d9' },
  orange: { label: L('برتقالي', 'Orange'), hex: '#e0692c' },
  blue: { label: L('أزرق', 'Blue'), hex: '#3f5f82' },
  navy: { label: L('كحلي', 'Navy'), hex: '#26324a' },
  'light-blue': { label: L('أزرق فاتح', 'Light Blue'), hex: '#a9c4dd' },
  green: { label: L('أخضر', 'Green'), hex: '#9fb8a3' },
  pink: { label: L('وردي', 'Pink'), hex: '#efc5c8' },
  teal: { label: L('تركواز', 'Teal'), hex: '#5f9ea0' },
  purple: { label: L('بنفسجي', 'Purple'), hex: '#a79bc9' },
  gold: { label: L('ذهبي', 'Gold'), hex: '#d8c29a' },
  gray: { label: L('رمادي', 'Gray'), hex: '#8a8c90' },
  'space-gray': { label: L('رمادي داكن', 'Space Gray'), hex: '#5d5e62' },
  midnight: { label: L('ميدنايت', 'Midnight'), hex: '#252c38' },
  starlight: { label: L('ستارلايت', 'Starlight'), hex: '#eae1d2' },
  'sky-blue': { label: L('أزرق سماوي', 'Sky Blue'), hex: '#bcd3e6' },
  yellow: { label: L('أصفر', 'Yellow'), hex: '#f1dc7a' },
  titanium: { label: L('تيتانيوم طبيعي', 'Natural Titanium'), hex: '#a8a39a' },
  'rose-gold': { label: L('روز جولد', 'Rose Gold'), hex: '#e3b7a5' },
  red: { label: L('أحمر', 'Red'), hex: '#b3262f' },
};

const STORAGE = {
  '128gb': L('128 جيجابايت', '128GB'),
  '256gb': L('256 جيجابايت', '256GB'),
  '512gb': L('512 جيجابايت', '512GB'),
  '1tb': L('1 تيرابايت', '1TB'),
};

const OPTION_NAMES = {
  storage: L('المساحة', 'Storage'),
  color: L('اللون', 'Color'),
  size: L('المقاس', 'Size'),
  edition: L('الإصدار', 'Edition'),
  model: L('الموديل', 'Model'),
  length: L('الطول', 'Length'),
};

const WARRANTY_AGENT = L('ضمان وكيل', 'Authorized distributor warranty');
const WARRANTY_STORE = L('ضمان المحل لمدة سنة', 'One-year store warranty');

const TBC = L('سيتم تأكيدها عند الإطلاق', 'To be confirmed at launch');

const spec = (key, ar, en, valueAr, valueEn = valueAr) => ({
  key,
  label: L(ar, en),
  value: L(valueAr, valueEn),
});
const group = (key, ar, en, items) => ({ key, title: L(ar, en), items });

/**
 * Build a product's options + variant matrix.
 * axes: { storage: ['256gb', ...], color: ['black', ...] } (any option keys)
 * price(opts) → number; stock(opts) → number; compareAt(opts) → number|null
 */
function matrix({
  skuPrefix,
  axes,
  price,
  stock = () => 8,
  compareAt = () => null,
  defaults = {},
  labels = {},
}) {
  const keys = Object.keys(axes);
  const options = keys.map((key) => ({
    key,
    name: OPTION_NAMES[key],
    values: axes[key].map((valueKey) => ({
      key: valueKey,
      label:
        labels[valueKey] ??
        (key === 'color'
          ? COLORS[valueKey].label
          : key === 'storage'
            ? STORAGE[valueKey]
            : L(valueKey, valueKey)),
      hex: key === 'color' ? COLORS[valueKey].hex : null,
    })),
  }));
  let combos = [{}];
  for (const key of keys)
    combos = combos.flatMap((c) => axes[key].map((v) => ({ ...c, [key]: v })));
  const variants = combos.map((opts) => ({
    sku: [skuPrefix, ...keys.map((k) => opts[k])].join('-').toUpperCase(),
    options: opts,
    price: price(opts),
    compareAtPrice: compareAt(opts),
    stock: stock(opts),
    isDefault: keys.every((k) => (defaults[k] ?? axes[k][0]) === opts[k]),
  }));
  return { options, variants };
}

export const BRANDS = [
  {
    slug: 'apple',
    name: L('Apple', 'Apple'),
    description: L(
      'آيفون وماك وآيباد وساعات Apple وإيربودز وإكسسوارات.',
      'iPhone, Mac, iPad, Apple Watch, AirPods and accessories.',
    ),
    sortOrder: 1,
  },
  { slug: 'samsung', name: L('Samsung', 'Samsung'), description: null, sortOrder: 2 },
  { slug: 'xiaomi', name: L('Xiaomi', 'Xiaomi'), description: null, sortOrder: 3 },
  { slug: 'honor', name: L('Honor', 'Honor'), description: null, sortOrder: 4 },
  { slug: 'oppo', name: L('OPPO', 'OPPO'), description: null, sortOrder: 5 },
  { slug: 'sony', name: L('Sony', 'Sony'), description: null, sortOrder: 6 },
  { slug: 'anker', name: L('Anker', 'Anker'), description: null, sortOrder: 7 },
];

export const CATEGORIES = [
  { slug: 'phones', parentSlug: null, name: L('موبايلات', 'Phones'), icon: 'phone', sortOrder: 1 },
  { slug: 'tablets', parentSlug: null, name: L('تابلت', 'Tablets'), icon: 'tablet', sortOrder: 2 },
  { slug: 'laptops', parentSlug: null, name: L('لابتوب', 'Laptops'), icon: 'laptop', sortOrder: 3 },
  {
    slug: 'macbook',
    parentSlug: 'laptops',
    name: L('ماك بوك', 'MacBook'),
    icon: 'laptop',
    sortOrder: 1,
    showOnHome: false,
  },
  {
    slug: 'watches',
    parentSlug: null,
    name: L('ساعات ذكية', 'Watches'),
    icon: 'watch',
    sortOrder: 4,
  },
  {
    slug: 'audio',
    parentSlug: null,
    name: L('سماعات', 'Headphones & Earbuds'),
    icon: 'headphones',
    sortOrder: 5,
  },
  { slug: 'gaming', parentSlug: null, name: L('ألعاب', 'Gaming'), icon: 'gamepad', sortOrder: 6 },
  {
    slug: 'playstation-5',
    parentSlug: 'gaming',
    name: L('بلايستيشن 5', 'PlayStation 5'),
    icon: 'gamepad',
    sortOrder: 1,
    showOnHome: false,
  },
  {
    slug: 'scooters',
    parentSlug: null,
    name: L('سكوتر كهربائي', 'Electric Scooters'),
    icon: 'scooter',
    sortOrder: 7,
  },
  {
    slug: 'accessories',
    parentSlug: null,
    name: L('إكسسوارات', 'Accessories'),
    icon: 'plug',
    sortOrder: 8,
  },
];

const phoneSpecs = (display, chip, camera, battery) => [
  group('display', 'الشاشة', 'Display', [spec('size', 'المقاس', 'Size', display)]),
  group('performance', 'الأداء', 'Performance', [spec('chip', 'المعالج', 'Chip', chip)]),
  group('camera', 'الكاميرا', 'Camera', [spec('main', 'الكاميرا الأساسية', 'Main camera', camera)]),
  group('battery', 'البطارية', 'Battery', [spec('charging', 'الشحن', 'Charging', battery)]),
  group('connectivity', 'الاتصال', 'Connectivity', [
    spec('sim', 'الشريحة', 'SIM', 'شريحة + eSIM', 'Nano-SIM + eSIM'),
    spec('network', 'الشبكة', 'Network', '5G'),
  ]),
];

const tbcSpecs = [
  group('overview', 'نظرة عامة', 'Overview', [
    spec('display', 'الشاشة', 'Display', TBC.ar, TBC.en),
    spec('chip', 'المعالج', 'Chip', TBC.ar, TBC.en),
    spec('camera', 'الكاميرا', 'Camera', TBC.ar, TBC.en),
    spec('battery', 'البطارية', 'Battery', TBC.ar, TBC.en),
  ]),
];

export const PRODUCTS = [
  {
    slug: 'iphone-18-pro',
    brand: 'apple',
    categories: ['phones'],
    model: 'iPhone 18 Pro',
    device: 'phone',
    name: L('iPhone 18 Pro', 'iPhone 18 Pro'),
    subtitle: L(
      'الجديد من Apple — متاح بكل المساحات',
      'New from Apple — available in every storage',
    ),
    description: L(
      'iPhone 18 Pro متاح الآن في MALEK STORE. اختار المساحة واللون المناسبين ليك، وفريقنا يتابع معاك بعد الشراء. التفاصيل الفنية الكاملة يتم تأكيدها عند الإطلاق.',
      'iPhone 18 Pro is available now at MALEK STORE. Choose the storage and colour that suit you, and our team follows up with you after purchase. Full technical details are confirmed at launch.',
    ),
    availability: 'available',
    isNew: true,
    isFeatured: true,
    releaseDate: '-12d',
    warranty: WARRANTY_AGENT,
    bestSeller: 96,
    ...matrix({
      skuPrefix: 'IP18P',
      axes: { storage: ['256gb', '512gb', '1tb'], color: ['orange', 'black', 'silver', 'blue'] },
      price: (o) =>
        ({ '256gb': 72000, '512gb': 82000, '1tb': 94000 })[o.storage] +
        (o.color === 'orange' ? 1500 : 0),
      stock: (o) =>
        o.storage === '1tb' && o.color === 'orange'
          ? 0
          : o.color === 'blue' && o.storage === '512gb'
            ? 2
            : 6,
    }),
    specGroups: tbcSpecs,
    relations: {
      accessory: [
        'magsafe-clear-case-18-pro',
        'apple-20w-usb-c-adapter',
        'usb-c-cable',
        'anker-power-bank-10k',
      ],
      similar: ['iphone-18-pro-max', 'iphone-17', 'galaxy-s26-ultra'],
      recommended: ['airpods-pro-3', 'apple-watch-series-11'],
    },
  },
  {
    slug: 'iphone-18-pro-max',
    brand: 'apple',
    categories: ['phones'],
    model: 'iPhone 18 Pro Max',
    device: 'phone',
    name: L('iPhone 18 Pro Max', 'iPhone 18 Pro Max'),
    subtitle: L('أكبر شاشة في العائلة الجديدة', 'The biggest screen in the new line-up'),
    description: L(
      'iPhone 18 Pro Max متاح الآن في MALEK STORE بمساحات وألوان مختلفة. التفاصيل الفنية الكاملة يتم تأكيدها عند الإطلاق.',
      'iPhone 18 Pro Max is available now at MALEK STORE in several storage sizes and colours. Full technical details are confirmed at launch.',
    ),
    availability: 'available',
    isNew: true,
    isFeatured: true,
    releaseDate: '-12d',
    warranty: WARRANTY_AGENT,
    bestSeller: 92,
    ...matrix({
      skuPrefix: 'IP18PM',
      axes: { storage: ['256gb', '512gb', '1tb'], color: ['black', 'orange', 'silver', 'blue'] },
      price: (o) =>
        ({ '256gb': 80000, '512gb': 90000, '1tb': 102000 })[o.storage] +
        (o.color === 'orange' ? 1500 : 0),
      stock: (o) =>
        o.storage === '1tb' ? 1 : o.color === 'silver' && o.storage === '256gb' ? 0 : 5,
    }),
    specGroups: tbcSpecs,
    relations: {
      accessory: ['apple-20w-usb-c-adapter', 'usb-c-cable', 'anker-power-bank-10k'],
      similar: ['iphone-18-pro', 'galaxy-s26-ultra'],
      recommended: ['airpods-pro-3', 'apple-watch-ultra-3'],
    },
  },
  {
    slug: 'iphone-duo',
    brand: 'apple',
    categories: ['phones'],
    model: 'iPhone Duo',
    device: 'phone',
    previewColor: 'black',
    name: L('iPhone Duo', 'iPhone Duo'),
    subtitle: L('قريبًا في MALEK STORE', 'Coming soon to MALEK STORE'),
    description: L(
      'iPhone Duo جاي قريب. سجّل في قائمة الانتظار وهنبلغك أول ما يتوفر. الأسعار والمواصفات والألوان يتم الإعلان عنها لاحقًا.',
      'iPhone Duo is on its way. Join the waitlist and we will let you know as soon as it is available. Prices, specifications and colours will be announced later.',
    ),
    availability: 'coming_soon',
    isNew: true,
    isFeatured: true,
    releaseDate: null,
    warranty: null,
    bestSeller: 0,
    options: [],
    variants: [],
    specGroups: tbcSpecs,
    relations: { similar: ['iphone-18-pro', 'iphone-18-pro-max'] },
  },
  {
    slug: 'iphone-17',
    brand: 'apple',
    categories: ['phones'],
    model: 'iPhone 17',
    device: 'phone-dual',
    name: L('iPhone 17', 'iPhone 17'),
    subtitle: L('اختيار ذكي لكل يوم', 'A smart everyday choice'),
    description: L(
      'iPhone 17 بمساحتين وأكتر من لون.',
      'iPhone 17 in two storage sizes and several colours.',
    ),
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-380d',
    warranty: WARRANTY_AGENT,
    bestSeller: 88,
    ...matrix({
      skuPrefix: 'IP17',
      axes: { storage: ['256gb', '512gb'], color: ['black', 'white', 'blue', 'green'] },
      price: (o) => (o.storage === '256gb' ? 48000 : 58000),
      stock: (o) => (o.color === 'green' ? 3 : 9),
    }),
    specGroups: phoneSpecs('6.3 بوصة', 'A-series', '48 ميجابكسل', 'شحن سريع + MagSafe'),
    relations: {
      accessory: ['apple-20w-usb-c-adapter', 'usb-c-cable'],
      similar: ['iphone-16', 'galaxy-a57'],
    },
  },
  {
    slug: 'iphone-16',
    brand: 'apple',
    categories: ['phones'],
    model: 'iPhone 16',
    device: 'phone-dual',
    name: L('iPhone 16', 'iPhone 16'),
    subtitle: L('سعر أقل لفترة محدودة', 'Lower price for a limited time'),
    description: L(
      'iPhone 16 بسعر مخفض ضمن عروض الأسعار.',
      'iPhone 16 at a reduced price in our price-drop offers.',
    ),
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-740d',
    warranty: WARRANTY_AGENT,
    bestSeller: 80,
    ...matrix({
      skuPrefix: 'IP16',
      axes: { storage: ['128gb', '256gb'], color: ['black', 'pink', 'teal'] },
      price: (o) => (o.storage === '128gb' ? 38000 : 43000),
      compareAt: (o) => (o.storage === '128gb' ? 41000 : 46500),
      stock: () => 7,
    }),
    specGroups: phoneSpecs('6.1 بوصة', 'A-series', '48 ميجابكسل', 'شحن سريع'),
    relations: { accessory: ['usb-c-cable'], similar: ['iphone-17'] },
  },
  {
    slug: 'galaxy-s26-ultra',
    brand: 'samsung',
    categories: ['phones'],
    model: 'Galaxy S26 Ultra',
    device: 'phone',
    name: L('Galaxy S26 Ultra', 'Galaxy S26 Ultra'),
    subtitle: L('سعر جديد — وفر أكتر', 'New price — save more'),
    description: L(
      'Galaxy S26 Ultra بسعر مخفض لفترة محدودة.',
      'Galaxy S26 Ultra at a reduced price for a limited time.',
    ),
    availability: 'available',
    isNew: false,
    isFeatured: true,
    releaseDate: '-220d',
    warranty: WARRANTY_AGENT,
    bestSeller: 84,
    ...matrix({
      skuPrefix: 'GS26U',
      axes: { storage: ['256gb', '512gb'], color: ['black', 'titanium', 'blue'] },
      price: (o) => (o.storage === '256gb' ? 62000 : 70000),
      compareAt: (o) => (o.storage === '256gb' ? 66000 : 74000),
      stock: (o) => (o.color === 'blue' ? 0 : 5),
    }),
    specGroups: phoneSpecs('6.9 بوصة', 'Snapdragon', '200 ميجابكسل', 'شحن سريع 45 وات'),
    relations: {
      accessory: ['anker-power-bank-10k', 'usb-c-cable'],
      similar: ['iphone-18-pro-max', 'galaxy-a57'],
      recommended: ['galaxy-buds-3-pro', 'galaxy-watch-8'],
    },
  },
  {
    slug: 'galaxy-a57',
    brand: 'samsung',
    categories: ['phones'],
    model: 'Galaxy A57',
    device: 'phone-dual',
    name: L('Galaxy A57', 'Galaxy A57'),
    subtitle: L('قيمة ممتازة مقابل السعر', 'Great value for money'),
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-160d',
    warranty: WARRANTY_AGENT,
    bestSeller: 78,
    ...matrix({
      skuPrefix: 'GA57',
      axes: { storage: ['128gb', '256gb'], color: ['navy', 'light-blue'] },
      price: (o) => (o.storage === '128gb' ? 17500 : 19500),
      stock: () => 12,
    }),
    specGroups: phoneSpecs('6.7 بوصة', 'Exynos', '50 ميجابكسل', 'شحن سريع 25 وات'),
    relations: { similar: ['redmi-note-15-pro', 'honor-400', 'oppo-reno-14'] },
  },
  {
    slug: 'redmi-note-15-pro',
    brand: 'xiaomi',
    categories: ['phones'],
    model: 'Redmi Note 15 Pro',
    device: 'phone-dual',
    name: L('Redmi Note 15 Pro', 'Redmi Note 15 Pro'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: true,
    isFeatured: false,
    releaseDate: '-40d',
    warranty: WARRANTY_AGENT,
    bestSeller: 74,
    ...matrix({
      skuPrefix: 'RN15P',
      axes: { storage: ['256gb'], color: ['black', 'blue', 'purple'] },
      price: () => 14000,
      stock: (o) => (o.color === 'purple' ? 2 : 10),
    }),
    specGroups: phoneSpecs('6.67 بوصة', 'Dimensity', '200 ميجابكسل', 'شحن سريع 67 وات'),
    relations: { similar: ['galaxy-a57', 'honor-400'] },
  },
  {
    slug: 'honor-400',
    brand: 'honor',
    categories: ['phones'],
    model: 'Honor 400',
    device: 'phone-dual',
    name: L('Honor 400', 'Honor 400'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-120d',
    warranty: WARRANTY_STORE,
    bestSeller: 60,
    ...matrix({
      skuPrefix: 'HN400',
      axes: { storage: ['256gb', '512gb'], color: ['black', 'gold'] },
      price: (o) => (o.storage === '256gb' ? 21000 : 24000),
      stock: () => 6,
    }),
    specGroups: phoneSpecs('6.55 بوصة', 'Snapdragon', '200 ميجابكسل', 'شحن سريع 66 وات'),
    relations: { similar: ['oppo-reno-14', 'redmi-note-15-pro'] },
  },
  {
    slug: 'oppo-reno-14',
    brand: 'oppo',
    categories: ['phones'],
    model: 'Reno 14',
    device: 'phone-dual',
    name: L('OPPO Reno 14', 'OPPO Reno 14'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-100d',
    warranty: WARRANTY_AGENT,
    bestSeller: 58,
    ...matrix({
      skuPrefix: 'RENO14',
      axes: { storage: ['256gb'], color: ['green', 'gray'] },
      price: () => 23500,
      stock: () => 4,
    }),
    specGroups: phoneSpecs('6.59 بوصة', 'Dimensity', '50 ميجابكسل', 'شحن سريع 80 وات'),
    relations: { similar: ['honor-400', 'galaxy-a57'] },
  },
  {
    slug: 'ipad-air-11',
    brand: 'apple',
    categories: ['tablets'],
    model: 'iPad Air 11-inch',
    device: 'tablet',
    name: L('iPad Air مقاس 11 بوصة', 'iPad Air 11-inch'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-200d',
    warranty: WARRANTY_AGENT,
    bestSeller: 70,
    ...matrix({
      skuPrefix: 'IPADAIR11',
      axes: { storage: ['128gb', '256gb'], color: ['space-gray', 'blue', 'purple'] },
      price: (o) => (o.storage === '128gb' ? 32000 : 38000),
      stock: () => 5,
    }),
    specGroups: [
      group('display', 'الشاشة', 'Display', [spec('size', 'المقاس', 'Size', '11 بوصة', '11-inch')]),
      group('performance', 'الأداء', 'Performance', [spec('chip', 'المعالج', 'Chip', 'M-series')]),
      group('connectivity', 'الاتصال', 'Connectivity', [
        spec('wifi', 'الشبكة', 'Network', 'Wi-Fi'),
      ]),
    ],
    relations: { accessory: ['apple-20w-usb-c-adapter'], similar: ['ipad-11', 'galaxy-tab-s11'] },
  },
  {
    slug: 'ipad-11',
    brand: 'apple',
    categories: ['tablets'],
    model: 'iPad 11-inch',
    device: 'tablet',
    name: L('iPad مقاس 11 بوصة', 'iPad 11-inch'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-210d',
    warranty: WARRANTY_AGENT,
    bestSeller: 72,
    ...matrix({
      skuPrefix: 'IPAD11',
      axes: { storage: ['128gb', '256gb'], color: ['silver', 'blue', 'pink', 'yellow'] },
      price: (o) => (o.storage === '128gb' ? 21000 : 26000),
      stock: (o) => (o.color === 'yellow' ? 0 : 6),
    }),
    specGroups: [
      group('display', 'الشاشة', 'Display', [spec('size', 'المقاس', 'Size', '11 بوصة', '11-inch')]),
      group('performance', 'الأداء', 'Performance', [spec('chip', 'المعالج', 'Chip', 'A-series')]),
    ],
    relations: { similar: ['ipad-air-11'] },
  },
  {
    slug: 'galaxy-tab-s11',
    brand: 'samsung',
    categories: ['tablets'],
    model: 'Galaxy Tab S11',
    device: 'tablet',
    name: L('Galaxy Tab S11', 'Galaxy Tab S11'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: true,
    isFeatured: false,
    releaseDate: '-30d',
    warranty: WARRANTY_AGENT,
    bestSeller: 55,
    ...matrix({
      skuPrefix: 'GTABS11',
      axes: { storage: ['128gb', '256gb'], color: ['gray', 'silver'] },
      price: (o) => (o.storage === '128gb' ? 36000 : 40000),
      stock: () => 3,
    }),
    specGroups: [
      group('display', 'الشاشة', 'Display', [spec('size', 'المقاس', 'Size', '11 بوصة', '11-inch')]),
    ],
    relations: { similar: ['ipad-air-11'] },
  },
  {
    slug: 'apple-watch-series-11',
    brand: 'apple',
    categories: ['watches'],
    model: 'Apple Watch Series 11',
    device: 'watch',
    name: L('Apple Watch Series 11', 'Apple Watch Series 11'),
    subtitle: L('ضمن باقة إيربودز + ساعة', 'Part of the AirPods + Watch bundle'),
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: true,
    releaseDate: '-370d',
    warranty: WARRANTY_AGENT,
    bestSeller: 82,
    ...matrix({
      skuPrefix: 'AWS11',
      axes: { size: ['42mm', '46mm'], color: ['black', 'rose-gold', 'silver'] },
      labels: { '42mm': L('42 مم', '42mm'), '46mm': L('46 مم', '46mm') },
      price: (o) => (o.size === '42mm' ? 22000 : 24500),
      stock: (o) => (o.color === 'rose-gold' && o.size === '46mm' ? 0 : 5),
    }),
    specGroups: [
      group('case', 'الهيكل', 'Case', [
        spec('material', 'الخامة', 'Material', 'ألومنيوم', 'Aluminium'),
      ]),
      group('health', 'الصحة واللياقة', 'Health & fitness', [
        spec(
          'sensors',
          'الحساسات',
          'Sensors',
          'نبض القلب، النوم، النشاط',
          'Heart rate, sleep, activity',
        ),
      ]),
      group('battery', 'البطارية', 'Battery', [
        spec('life', 'عمر البطارية', 'Battery life', 'يوم كامل', 'All day'),
      ]),
    ],
    relations: {
      accessory: ['usb-c-cable'],
      similar: ['apple-watch-ultra-3', 'galaxy-watch-8'],
      recommended: ['airpods-4'],
    },
  },
  {
    slug: 'apple-watch-ultra-3',
    brand: 'apple',
    categories: ['watches'],
    model: 'Apple Watch Ultra 3',
    device: 'watch',
    name: L('Apple Watch Ultra 3', 'Apple Watch Ultra 3'),
    subtitle: L('نفدت الكمية حاليًا', 'Currently sold out'),
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-360d',
    warranty: WARRANTY_AGENT,
    bestSeller: 66,
    ...matrix({
      skuPrefix: 'AWU3',
      axes: { color: ['titanium', 'black'] },
      price: () => 42000,
      stock: () => 0,
    }),
    specGroups: [
      group('case', 'الهيكل', 'Case', [
        spec('size', 'المقاس', 'Size', '49 مم', '49mm'),
        spec('material', 'الخامة', 'Material', 'تيتانيوم', 'Titanium'),
      ]),
    ],
    relations: { similar: ['apple-watch-series-11'] },
  },
  {
    slug: 'galaxy-watch-8',
    brand: 'samsung',
    categories: ['watches'],
    model: 'Galaxy Watch 8',
    device: 'watch',
    name: L('Galaxy Watch 8', 'Galaxy Watch 8'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-90d',
    warranty: WARRANTY_AGENT,
    bestSeller: 52,
    ...matrix({
      skuPrefix: 'GW8',
      axes: { size: ['40mm', '44mm'], color: ['black', 'silver'] },
      labels: { '40mm': L('40 مم', '40mm'), '44mm': L('44 مم', '44mm') },
      price: (o) => (o.size === '40mm' ? 14000 : 15500),
      stock: () => 4,
    }),
    specGroups: [
      group('health', 'الصحة واللياقة', 'Health & fitness', [
        spec('sensors', 'الحساسات', 'Sensors', 'نبض القلب، النوم', 'Heart rate, sleep'),
      ]),
    ],
    relations: { similar: ['apple-watch-series-11'] },
  },
  {
    slug: 'airpods-pro-3',
    brand: 'apple',
    categories: ['audio'],
    model: 'AirPods Pro 3',
    device: 'earbuds',
    name: L('AirPods Pro 3', 'AirPods Pro 3'),
    subtitle: L('عرض لفترة محدودة', 'Limited-time offer'),
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: true,
    releaseDate: '-360d',
    warranty: WARRANTY_AGENT,
    bestSeller: 94,
    ...matrix({
      skuPrefix: 'APP3',
      axes: { color: ['white'] },
      // Regular price; the time-bound "airpods-pro-3-limited" offer (−10%) sets the selling price.
      price: () => 15000,
      stock: () => 14,
    }),
    specGroups: [
      group('audio', 'الصوت', 'Audio', [
        spec('anc', 'عزل الضوضاء', 'Noise control', 'عزل نشط للضوضاء', 'Active noise cancellation'),
      ]),
      group('battery', 'البطارية', 'Battery', [
        spec('case', 'علبة الشحن', 'Charging case', 'USB-C'),
      ]),
    ],
    relations: {
      accessory: ['usb-c-cable'],
      similar: ['airpods-4', 'galaxy-buds-3-pro'],
      recommended: ['apple-watch-series-11'],
    },
  },
  {
    slug: 'airpods-4',
    brand: 'apple',
    categories: ['audio'],
    model: 'AirPods 4',
    device: 'earbuds',
    name: L('AirPods 4', 'AirPods 4'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-370d',
    warranty: WARRANTY_AGENT,
    bestSeller: 86,
    ...matrix({
      skuPrefix: 'AP4',
      axes: { model: ['standard', 'anc'], color: ['white'] },
      labels: { standard: L('عادي', 'Standard'), anc: L('بعزل الضوضاء', 'With ANC') },
      price: (o) => (o.model === 'standard' ? 7500 : 9500),
      stock: () => 10,
    }),
    specGroups: [
      group('audio', 'الصوت', 'Audio', [
        spec('fit', 'التصميم', 'Design', 'تصميم مفتوح', 'Open-ear design'),
      ]),
    ],
    relations: { similar: ['airpods-pro-3'], recommended: ['apple-watch-series-11'] },
  },
  {
    slug: 'galaxy-buds-3-pro',
    brand: 'samsung',
    categories: ['audio'],
    model: 'Galaxy Buds 3 Pro',
    device: 'earbuds',
    name: L('Galaxy Buds 3 Pro', 'Galaxy Buds 3 Pro'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-420d',
    warranty: WARRANTY_AGENT,
    bestSeller: 50,
    ...matrix({
      skuPrefix: 'GB3P',
      axes: { color: ['silver', 'white'] },
      price: () => 9000,
      stock: () => 6,
    }),
    specGroups: [
      group('audio', 'الصوت', 'Audio', [
        spec('anc', 'عزل الضوضاء', 'Noise control', 'عزل نشط للضوضاء', 'Active noise cancellation'),
      ]),
    ],
    relations: { similar: ['airpods-pro-3'] },
  },
  {
    slug: 'macbook-air-13',
    brand: 'apple',
    categories: ['macbook', 'laptops'],
    model: 'MacBook Air 13-inch',
    device: 'laptop',
    name: L('MacBook Air مقاس 13 بوصة', 'MacBook Air 13-inch'),
    subtitle: L('معاه شاحن هدية', 'Comes with a free charger'),
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: true,
    releaseDate: '-190d',
    warranty: WARRANTY_AGENT,
    bestSeller: 76,
    ...matrix({
      skuPrefix: 'MBA13',
      axes: { storage: ['256gb', '512gb'], color: ['midnight', 'starlight', 'sky-blue', 'silver'] },
      price: (o) => (o.storage === '256gb' ? 62000 : 74000),
      stock: (o) => (o.color === 'sky-blue' ? 2 : 5),
    }),
    specGroups: [
      group('display', 'الشاشة', 'Display', [
        spec('size', 'المقاس', 'Size', '13.6 بوصة', '13.6-inch'),
      ]),
      group('performance', 'الأداء', 'Performance', [
        spec('chip', 'المعالج', 'Chip', 'M-series'),
        spec('memory', 'الذاكرة', 'Memory', '16 جيجابايت', '16GB'),
      ]),
      group('ports', 'المنافذ', 'Ports', [spec('ports', 'المنافذ', 'Ports', 'USB-C ×2 + MagSafe')]),
      group('weight', 'الوزن', 'Weight', [
        spec('weight', 'الوزن', 'Weight', 'أقل من 1.3 كجم', 'Under 1.3 kg'),
      ]),
    ],
    relations: { accessory: ['usb-c-cable', 'anker-power-bank-10k'], similar: ['macbook-pro-14'] },
  },
  {
    slug: 'macbook-pro-14',
    brand: 'apple',
    categories: ['macbook', 'laptops'],
    model: 'MacBook Pro 14-inch',
    device: 'laptop',
    name: L('MacBook Pro مقاس 14 بوصة', 'MacBook Pro 14-inch'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-330d',
    warranty: WARRANTY_AGENT,
    bestSeller: 64,
    ...matrix({
      skuPrefix: 'MBP14',
      axes: { storage: ['512gb', '1tb'], color: ['black', 'silver'] },
      price: (o) => (o.storage === '512gb' ? 105000 : 125000),
      stock: () => 3,
    }),
    specGroups: [
      group('display', 'الشاشة', 'Display', [
        spec('size', 'المقاس', 'Size', '14.2 بوصة', '14.2-inch'),
      ]),
      group('performance', 'الأداء', 'Performance', [
        spec('chip', 'المعالج', 'Chip', 'M-series Pro'),
      ]),
    ],
    relations: { similar: ['macbook-air-13'] },
  },
  {
    slug: 'playstation-5-slim',
    brand: 'sony',
    categories: ['playstation-5', 'gaming'],
    model: 'PlayStation 5 Slim',
    device: 'console',
    name: L('PlayStation 5 Slim', 'PlayStation 5 Slim'),
    subtitle: L('عرض سريع لفترة قصيرة', 'Flash offer for a short time'),
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: true,
    releaseDate: '-600d',
    warranty: WARRANTY_STORE,
    bestSeller: 90,
    ...matrix({
      skuPrefix: 'PS5S',
      axes: { edition: ['disc', 'digital'], color: ['white'] },
      labels: { disc: L('بقارئ أقراص', 'Disc edition'), digital: L('ديجيتال', 'Digital edition') },
      // Regular prices; the "ps5-flash-offer" (−2,000 EGP while it runs) sets the selling price.
      price: (o) => (o.edition === 'disc' ? 34000 : 29500),
      stock: (o) => (o.edition === 'digital' ? 1 : 6),
    }),
    specGroups: [
      group('storage', 'التخزين', 'Storage', [
        spec('ssd', 'مساحة التخزين', 'Storage', '1 تيرابايت SSD', '1TB SSD'),
      ]),
      group('video', 'الصورة', 'Video', [spec('output', 'الدقة', 'Output', 'حتى 4K', 'Up to 4K')]),
      group('box', 'في العلبة', 'In the box', [
        spec(
          'controller',
          'ذراع التحكم',
          'Controller',
          'DualSense واحد',
          'One DualSense controller',
        ),
      ]),
    ],
    relations: { accessory: ['dualsense-controller'], recommended: ['dualsense-controller'] },
  },
  {
    slug: 'dualsense-controller',
    brand: 'sony',
    categories: ['gaming', 'accessories'],
    model: 'DualSense',
    device: 'controller',
    name: L('ذراع DualSense', 'DualSense Controller'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-700d',
    warranty: WARRANTY_STORE,
    bestSeller: 68,
    ...matrix({
      skuPrefix: 'DS5',
      axes: { color: ['white', 'black', 'red'] },
      price: () => 4200,
      stock: (o) => (o.color === 'red' ? 0 : 9),
    }),
    specGroups: [
      group('connectivity', 'الاتصال', 'Connectivity', [
        spec('conn', 'الاتصال', 'Connection', 'Bluetooth + USB-C'),
      ]),
    ],
    relations: { similar: [] },
  },
  {
    slug: 'xiaomi-electric-scooter-5',
    brand: 'xiaomi',
    categories: ['scooters'],
    model: 'Electric Scooter 5',
    device: 'scooter',
    name: L('سكوتر شاومي الكهربائي 5', 'Xiaomi Electric Scooter 5'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: true,
    isFeatured: false,
    releaseDate: '-60d',
    warranty: WARRANTY_STORE,
    bestSeller: 48,
    ...matrix({
      skuPrefix: 'XES5',
      axes: { color: ['black'] },
      price: () => 26000,
      stock: () => 3,
    }),
    specGroups: [
      group('performance', 'الأداء', 'Performance', [
        spec('speed', 'أقصى سرعة', 'Top speed', '25 كم/س', '25 km/h'),
        spec('range', 'المسافة', 'Range', 'حتى 45 كم', 'Up to 45 km'),
      ]),
      group('build', 'التصميم', 'Build', [
        spec('tires', 'الإطارات', 'Tyres', '10 بوصة', '10-inch'),
        spec('fold', 'الطي', 'Folding', 'قابل للطي', 'Foldable'),
      ]),
    ],
    relations: { similar: [] },
  },
  {
    slug: 'apple-20w-usb-c-adapter',
    brand: 'apple',
    categories: ['accessories'],
    model: '20W USB-C Power Adapter',
    device: 'charger',
    name: L('شاحن Apple USB-C بقوة 20 وات', 'Apple 20W USB-C Power Adapter'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-900d',
    warranty: WARRANTY_AGENT,
    bestSeller: 85,
    ...matrix({
      skuPrefix: 'A20W',
      axes: { color: ['white'] },
      price: () => 1200,
      stock: () => 30,
    }),
    specGroups: [
      group('power', 'الطاقة', 'Power', [spec('output', 'القدرة', 'Output', '20 وات', '20W')]),
    ],
    relations: { similar: ['usb-c-cable'] },
  },
  {
    slug: 'magsafe-clear-case-18-pro',
    brand: 'apple',
    categories: ['accessories'],
    model: 'Clear Case with MagSafe',
    device: 'case',
    name: L('جراب شفاف MagSafe لـ iPhone 18 Pro', 'Clear Case with MagSafe for iPhone 18 Pro'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: true,
    isFeatured: false,
    releaseDate: '-12d',
    warranty: null,
    bestSeller: 62,
    ...matrix({
      skuPrefix: 'CASE18P',
      axes: { color: ['white'] },
      labels: {},
      price: () => 2400,
      compareAt: () => 2900,
      stock: () => 15,
    }),
    specGroups: [
      group('compat', 'التوافق', 'Compatibility', [
        spec('fits', 'متوافق مع', 'Fits', 'iPhone 18 Pro'),
      ]),
    ],
    relations: { similar: [] },
  },
  {
    slug: 'usb-c-cable',
    brand: 'apple',
    categories: ['accessories'],
    model: 'USB-C Charge Cable',
    device: 'cable',
    name: L('كابل شحن USB-C', 'USB-C Charge Cable'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-800d',
    warranty: WARRANTY_AGENT,
    bestSeller: 83,
    ...matrix({
      skuPrefix: 'USBC',
      axes: { length: ['1m', '2m'], color: ['white'] },
      labels: { '1m': L('1 متر', '1 m'), '2m': L('2 متر', '2 m') },
      price: (o) => (o.length === '1m' ? 900 : 1200),
      stock: () => 25,
    }),
    specGroups: [
      group('spec', 'المواصفات', 'Specifications', [
        spec('type', 'النوع', 'Type', 'USB-C إلى USB-C', 'USB-C to USB-C'),
      ]),
    ],
    relations: { similar: ['apple-20w-usb-c-adapter'] },
  },
  {
    slug: 'anker-power-bank-10k',
    brand: 'anker',
    categories: ['accessories'],
    model: 'Power Bank 10,000mAh',
    device: 'powerbank',
    name: L('باور بانك Anker بسعة 10,000 مللي أمبير', 'Anker Power Bank 10,000mAh'),
    subtitle: null,
    description: null,
    availability: 'available',
    isNew: false,
    isFeatured: false,
    releaseDate: '-300d',
    warranty: WARRANTY_STORE,
    bestSeller: 57,
    ...matrix({
      skuPrefix: 'ANK10K',
      axes: { color: ['black', 'white'] },
      price: () => 2100,
      stock: () => 11,
    }),
    specGroups: [
      group('battery', 'البطارية', 'Battery', [
        spec('capacity', 'السعة', 'Capacity', '10,000 مللي أمبير', '10,000mAh'),
      ]),
    ],
    relations: { similar: [] },
  },
];

export const OFFERS = [
  {
    slug: 'airpods-pro-3-limited',
    kind: 'limited_time',
    sortOrder: 1,
    featuredOnHome: true,
    showCountdown: true,
    title: L('AirPods Pro 3 بسعر خاص', 'AirPods Pro 3 at a special price'),
    subtitle: L('عرض لفترة محدودة — لحد ما الكمية تخلص', 'Limited time — while stock lasts'),
    badge: L('عرض محدود', 'Limited offer'),
    discountPercent: 10,
    startsAt: '-2d',
    endsAt: '+6d',
    cta: { label: L('شوف العرض', 'View offer'), href: '/product/airpods-pro-3' },
    products: [{ slug: 'airpods-pro-3', role: 'target' }],
  },
  {
    slug: 'airpods-watch-bundle',
    kind: 'bundle',
    sortOrder: 2,
    featuredOnHome: true,
    showCountdown: false,
    title: L('باقة AirPods 4 + Apple Watch Series 11', 'AirPods 4 + Apple Watch Series 11 bundle'),
    subtitle: L('خصم 10% (تجريبي) لما تشتريهم مع بعض', '10% (demo) off when bought together'),
    badge: L('باقة −10%', 'Bundle −10%'),
    discountPercent: 10,
    startsAt: '-5d',
    endsAt: '+20d',
    cta: { label: L('تفاصيل الباقة', 'Bundle details'), href: '/offers/airpods-watch-bundle' },
    products: [
      { slug: 'airpods-4', role: 'bundle_item' },
      { slug: 'apple-watch-series-11', role: 'bundle_item' },
    ],
  },
  {
    slug: 'galaxy-s26-ultra-price-drop',
    kind: 'price_drop',
    sortOrder: 3,
    featuredOnHome: true,
    showCountdown: false,
    title: L('سعر جديد على Galaxy S26 Ultra', 'New price on Galaxy S26 Ultra'),
    subtitle: L(
      'كان 66,000 — دلوقتي 62,000 (أسعار تجريبية)',
      'Was 66,000 — now 62,000 (demo prices)',
    ),
    badge: L('سعر أقل', 'Price drop'),
    startsAt: '-10d',
    endsAt: null,
    cta: { label: L('اشتري الآن', 'Shop now'), href: '/product/galaxy-s26-ultra' },
    products: [{ slug: 'galaxy-s26-ultra', role: 'target' }],
  },
  {
    slug: 'macbook-air-free-charger',
    kind: 'free_gift',
    sortOrder: 4,
    featuredOnHome: false,
    showCountdown: false,
    title: L('MacBook Air + شاحن هدية', 'MacBook Air + a free charger'),
    subtitle: L('شاحن USB-C هدية مع أي MacBook Air', 'A free USB-C charger with any MacBook Air'),
    badge: L('هدية', 'Free gift'),
    startsAt: '-3d',
    endsAt: '+25d',
    cta: { label: L('اختار جهازك', 'Choose yours'), href: '/product/macbook-air-13' },
    products: [
      { slug: 'macbook-air-13', role: 'target' },
      { slug: 'apple-20w-usb-c-adapter', role: 'gift' },
    ],
  },
  {
    slug: 'ps5-flash-offer',
    kind: 'flash',
    sortOrder: 5,
    featuredOnHome: true,
    showCountdown: true,
    title: L('عرض سريع على PlayStation 5 Slim', 'Flash offer on PlayStation 5 Slim'),
    subtitle: L('لمدة قصيرة جدًا', 'For a very short time'),
    badge: L('عرض سريع', 'Flash'),
    discountAmount: 2000,
    startsAt: '-6h',
    endsAt: '+42h',
    cta: { label: L('الحق العرض', 'Grab it'), href: '/product/playstation-5-slim' },
    products: [{ slug: 'playstation-5-slim', role: 'target' }],
  },
  {
    slug: 'accessories-promo-code',
    kind: 'promo_code',
    sortOrder: 6,
    featuredOnHome: false,
    showCountdown: false,
    title: L('كود خصم على الإكسسوارات', 'Promo code on accessories'),
    subtitle: L(
      'استخدم الكود DEMO10 (كود تجريبي) — التفعيل عند الدفع في المرحلة القادمة',
      'Use code DEMO10 (demo code) — applied at checkout in a later phase',
    ),
    badge: L('كود خصم', 'Promo code'),
    discountPercent: 10,
    promoCode: 'DEMO10',
    // Demo usage rule: each customer can redeem DEMO10 at most twice.
    maxRedemptionsPerCustomer: 2,
    startsAt: '-1d',
    endsAt: '+30d',
    cta: { label: L('تسوق الإكسسوارات', 'Shop accessories'), href: '/category/accessories' },
    products: [
      { slug: 'magsafe-clear-case-18-pro', role: 'target' },
      { slug: 'usb-c-cable', role: 'target' },
      { slug: 'anker-power-bank-10k', role: 'target' },
    ],
  },
  {
    slug: 'magsafe-case-price-drop',
    kind: 'price_drop',
    sortOrder: 7,
    featuredOnHome: false,
    showCountdown: false,
    title: L('جراب MagSafe بسعر أقل', 'MagSafe case for less'),
    subtitle: null,
    badge: L('سعر أقل', 'Price drop'),
    startsAt: '-4d',
    endsAt: '+14d',
    cta: { label: L('شوف المنتج', 'View product'), href: '/product/magsafe-clear-case-18-pro' },
    products: [{ slug: 'magsafe-clear-case-18-pro', role: 'target' }],
  },
];

export const ENTRIES = [
  {
    slug: 'iphone-18-pro-launch',
    type: 'campaign',
    isFeatured: true,
    publishAt: '-12d',
    state: 'available',
    eyebrow: L('جديد في MALEK STORE', 'New at MALEK STORE'),
    title: L('iPhone 18 Pro و iPhone 18 Pro Max', 'iPhone 18 Pro & iPhone 18 Pro Max'),
    subtitle: L(
      'وصلوا عندنا. اختار المساحة واللون اللي يناسبك واطلب من الفرع أو أونلاين قريب.',
      'They have arrived. Pick your storage and colour — order in store now, online soon.',
    ),
    media: {
      kind: 'image',
      device: 'phone-back',
      color: 'orange',
      alt: L('صورة توضيحية لـ iPhone 18 Pro', 'Illustration of iPhone 18 Pro'),
    },
    cta: { label: L('اتسوّق دلوقتي', 'Shop now'), href: '/product/iphone-18-pro' },
    secondaryCta: { label: L('شوف التفاصيل', 'View details'), href: '/product/iphone-18-pro-max' },
    products: ['iphone-18-pro', 'iphone-18-pro-max'],
  },
  {
    slug: 'iphone-duo-teaser',
    type: 'coming_soon',
    isFeatured: true,
    publishAt: '-4d',
    state: 'coming_soon',
    eyebrow: L('قريبًا', 'Coming soon'),
    title: L('iPhone Duo', 'iPhone Duo'),
    subtitle: L(
      'حاجة جديدة جاية. سجّل اهتمامك وهنبلغك أول ما يوصل.',
      'Something new is coming. Register your interest and we will tell you first.',
    ),
    media: {
      kind: 'image',
      device: 'phone-front',
      color: 'black',
      alt: L('صورة تشويقية لـ iPhone Duo', 'Teaser illustration for iPhone Duo'),
    },
    cta: { label: L('انضم لقائمة الانتظار', 'Join the waitlist'), href: '/product/iphone-duo' },
    products: ['iphone-duo'],
  },
  {
    slug: 'new-iphone-18-pro-release',
    type: 'new_release',
    isFeatured: true,
    publishAt: '-12d',
    releaseDate: '-12d',
    state: 'available',
    title: L('نزل iPhone 18 Pro', 'iPhone 18 Pro is here'),
    subtitle: L('متاح بكل المساحات في الفرع', 'Available in every storage in store'),
    excerpt: L(
      'iPhone 18 Pro و Pro Max متاحين دلوقتي في MALEK STORE.',
      'iPhone 18 Pro and Pro Max are now available at MALEK STORE.',
    ),
    body: L(
      'iPhone 18 Pro و iPhone 18 Pro Max متاحين دلوقتي في الفرع.\n\nتقدر تختار المساحة واللون، وفريقنا يساعدك في نقل بياناتك وضبط الجهاز.',
      'iPhone 18 Pro and iPhone 18 Pro Max are now available in store.\n\nPick your storage and colour, and our team will help you move your data and set up the phone.',
    ),
    media: {
      kind: 'image',
      device: 'phone-back',
      color: 'silver',
      alt: L('صورة توضيحية', 'Illustration'),
    },
    cta: { label: L('اختار جهازك', 'Choose yours'), href: '/product/iphone-18-pro' },
    products: ['iphone-18-pro', 'iphone-18-pro-max'],
  },
  {
    slug: 'new-galaxy-tab-s11',
    type: 'new_release',
    isFeatured: false,
    publishAt: '-30d',
    releaseDate: '-30d',
    state: 'available',
    title: L('Galaxy Tab S11 وصل', 'Galaxy Tab S11 has arrived'),
    subtitle: null,
    excerpt: L('تابلت سامسونج الجديد متاح في المتجر.', 'Samsung’s new tablet is in store.'),
    body: null,
    media: {
      kind: 'image',
      device: 'tablet-front',
      color: 'gray',
      alt: L('صورة توضيحية', 'Illustration'),
    },
    cta: { label: L('شوف المنتج', 'View product'), href: '/product/galaxy-tab-s11' },
    products: ['galaxy-tab-s11'],
  },
  {
    slug: 'accessories-price-update',
    type: 'offer_update',
    isFeatured: true,
    publishAt: '-4d',
    title: L('أسعار جديدة على الإكسسوارات', 'New prices on accessories'),
    subtitle: null,
    excerpt: L(
      'جرابات وكابلات وشواحن بأسعار أقل لفترة محدودة (بيانات تجريبية).',
      'Cases, cables and chargers for less, for a limited time (demo content).',
    ),
    body: null,
    media: {
      kind: 'image',
      device: 'case',
      color: 'white',
      alt: L('صورة توضيحية', 'Illustration'),
    },
    cta: { label: L('شوف العروض', 'See offers'), href: '/offers' },
    products: ['magsafe-clear-case-18-pro'],
  },
  {
    slug: 'trade-in-at-malek',
    type: 'news',
    isFeatured: true,
    publishAt: '-8d',
    title: L('بدّل جهازك القديم في الفرع', 'Trade in your old device in store'),
    subtitle: L('خبر تجريبي', 'Demo news item'),
    excerpt: L(
      'هات جهازك القديم وفريقنا يقيّمه ويحسبلك الفرق على الجديد.',
      'Bring your old device — our team will value it and work out the difference on a new one.',
    ),
    body: L(
      'خدمة الاستبدال متاحة في فرع العباسية.\n\nالتقييم النهائي بيكون بعد فحص الجهاز في الفرع.',
      'Trade-in is available at the Abbasseya branch.\n\nThe final valuation is confirmed after the device is inspected in store.',
    ),
    media: {
      kind: 'image',
      device: 'phone-front',
      color: 'blue',
      alt: L('صورة توضيحية', 'Illustration'),
    },
    cta: { label: L('اعرف أكتر', 'Learn more'), href: '/trade-in' },
    products: [],
  },
  {
    slug: 'repairs-consultation',
    type: 'news',
    isFeatured: false,
    publishAt: '-15d',
    title: L('استشارة صيانة قبل أي تصليح', 'A repair consultation before any fix'),
    subtitle: L('خبر تجريبي', 'Demo news item'),
    excerpt: L(
      'بنشخّص المشكلة الأول ونقولك التكلفة المتوقعة قبل ما نبدأ.',
      'We diagnose first and share the expected cost before we start.',
    ),
    body: null,
    media: {
      kind: 'image',
      device: 'phone-back-dual',
      color: 'green',
      alt: L('صورة توضيحية', 'Illustration'),
    },
    cta: { label: L('اعرف أكتر', 'Learn more'), href: '/repairs' },
    products: [],
  },
];

/** Arabic/transliteration search aliases; attached as product keywords when the English term matches. */
export const SEARCH_ALIASES = {
  iphone: 'ايفون آيفون',
  ipad: 'ايباد آيباد تابلت',
  macbook: 'ماك بوك ماكبوك لابتوب',
  airpods: 'ايربودز إيربودز سماعه سماعات',
  watch: 'ساعه ساعات',
  galaxy: 'جالاكسي جلاكسي',
  samsung: 'سامسونج',
  xiaomi: 'شاومي',
  redmi: 'ريدمي',
  honor: 'هونر',
  oppo: 'اوبو',
  apple: 'ابل',
  playstation: 'بلايستيشن بلاي ستيشن ps5',
  dualsense: 'دراع ذراع',
  scooter: 'سكوتر',
  anker: 'انكر',
  'power bank': 'باور بانك شاحن متنقل',
  adapter: 'شاحن',
  cable: 'كابل وصله',
  case: 'جراب كفر',
};
